"""
FourSquare Credentials
"""

class Credentials:

	CLIENT_ID = 'XJQMY0RTTTSYYN1MVX1GY5VKFRKFQQRNSQ1W1TAWXXOHOJTP' # your Foursquare ID
	CLIENT_SECRET = 'TEZBT4U1VIVCB4Q0LDOLEE4W5ZUI4TE3MOJQHVN23LP35KEO' # your Foursquare Secret
	VERSION = '20180605' # Foursquare API version
    
	def __init__(self):
		self.CLIENT_ID = CLIENT_ID
		self.CLIENT_SECRET = CLIENT_SECRET
		self.VERSION = VERSION