"""
FourSquare Credentials
"""

class Credentials:

	CLIENT_ID = 'OVF5BXCZDMLFWBRVWGI2TEGEODAO53T2SBHISUFUEKOUZFXD' # your Foursquare ID
	CLIENT_SECRET = 'ZLDEDVPAK5OJZK1NYCBT2QKLBV5UL0EEAOBN4UUNHD5H4MYS' # your Foursquare Secret
	VERSION = '20180605' # Foursquare API version
	ACCESS_TOKEN = 'HYJIQFEU4WZCU2NWXBL0TFRIX2LWXIJRNVZ1BXKWHPOHD1V3' #Gathered from the Forum
    
	def __init__(self):
		self.CLIENT_ID = CLIENT_ID
		self.CLIENT_SECRET = CLIENT_SECRET
		self.VERSION = VERSION
		self.ACCESS_TOKEN = ACCESS_TOKEN
